### ISSUE TITLE
 Inquiry Regarding Dataset Release Date

### ISSUE THREAD

**Issue by dianzizs** [eventbasedvision/SEVD#1]
Hope this message finds you well and thank you for your great work. We are very interested in your research and the accompanying dataset that you've mentioned in your recent publication. We believe it could significantly enhance our ongoing work.

Could you kindly share the anticipated timeline for the dataset release? Any information you can provide would be greatly appreciated.

**Comment by chakravarthi589** [comment]
Hi, 

Thanks for expressing your interest in our work. Please note, that the dataset will be made publically available by May 1st, 2024.
